# Generated by Django 5.1.7 on 2025-11-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryVault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
