# Generated by Django 5.1.7 on 2025-11-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryVault', '0002_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fullname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='video_description',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='video_description/'),
        ),
    ]
